### ISSUE TITLE
DbManager.cs

### ISSUE THREAD

**Issue by jimmy310** [wasichris/Tool-TemplateBasedDbDocumentMaker#1]
`(SELECT value
                          FROM sys.fn_listextendedproperty(NULL, 'schema', 'dbo', 'table', tb.TABLE_NAME, 'column', DEFAULT)
                          WHERE name = 'MS_Description'
                          AND objtype = 'COLUMN'
                          AND objname COLLATE Chinese_Taiwan_Stroke_CI_AS = col.COLUMN_NAME) AS 'Description'`
Maybe it can be changed to
`CASE
    WHEN tb.TABLE_TYPE = 'VIEW'
	THEN (SELECT value
      FROM sys.fn_listextendedproperty(NULL, 'schema', 'dbo', 'view', tb.TABLE_NAME, 'column', DEFAULT)
      WHERE name = 'MS_Description'
      AND objtype = 'COLUMN'
      AND objname COLLATE Chinese_Taiwan_Stroke_CI_AS = col.COLUMN_NAME)
	  ELSE (SELECT value
      FROM sys.fn_listextendedproperty(NULL, 'schema', 'dbo', 'table', tb.TABLE_NAME, 'column', DEFAULT)
      WHERE name = 'MS_Description'`

**Comment by wasichris** [comment]
What is the purpose? You can make a pull request if you found something could be better. Thanks.
